columns_list = [
    'DistanctToVendor',
    'FirstLastPropCase',
    'NameEmailCheck',
    'SingleHour',
    'ColoursNotChosen',
    'Income',
    'ZipPopulationDensity',
    'ZipPopulationDensity_AverageUsed',
    'AddressProvided',
    'AddressContainsNumericAndText',
    'PriceStart',
    'Hybrid',
    'Rating',
    'LifeTimeReviews',
    'Recommended',
    'SCR',
    'OCR'
]

columns_single_weekday = [
    'SingleWeekday_Sunday',
    'SingleWeekday_friday',
    'SingleWeekday_monday',
    'SingleWeekday_saturday',
    'SingleWeekday_sunday',
    'SingleWeekday_thursday',
    'SingleWeekday_tuesday',
    'SingleWeekday_wednesday',
]

columns_lead_TimeFrame = [
    'lead_TimeFrameCont_1 month',
    'lead_TimeFrameCont_2 weeks',
    'lead_TimeFrameCont_3 months',
    'lead_TimeFrameCont_beyond 3 months',
    'lead_TimeFrameCont_unknown'
]

columns_EmailDomainCat = [
    'EmailDomainCat_high',
    'EmailDomainCat_low',
    'EmailDomainCat_normal',
]

columns_Vehicle_FinanceMethod = [
    'Vehicle_FinanceMethod_cash',
    'Vehicle_FinanceMethod_finance',
    'Vehicle_FinanceMethod_lease',
    'Vehicle_FinanceMethod_unknown',
]

columns_BroadColour = [
    'BroadColour_beige',
    'BroadColour_black',
    'BroadColour_blue',
    'BroadColour_bronze',
    'BroadColour_gray',
    'BroadColour_green',
    'BroadColour_no preference',
    'BroadColour_orange',
    'BroadColour_red',
    'BroadColour_silver',
    'BroadColour_unknown',
    'BroadColour_white',
    'BroadColour_yellow',
]

columns_Gender = [
    'Gender_1f',
    'Gender_1m',
    'Gender_?',
    'Gender_?f',
    'Gender_?m',
    'Gender_f',
    'Gender_m',
    'Gender_unknown',
]

columns_CountryOfOrigin = [
    'CountryOfOrigin_asian',
    'CountryOfOrigin_east_asian_other',
    'CountryOfOrigin_europe',
    'CountryOfOrigin_unknown',
    'CountryOfOrigin_usa ',
]

columns_TelephonePreference = [
    'TelephonePreference_afternoon',
    'TelephonePreference_day',
    'TelephonePreference_evening',
    'TelephonePreference_morning',
    'TelephonePreference_nopreference',
    'TelephonePreference_unknown',
]

columns_Segment_Description = [
    'Segment_Description_compact truck',
    'Segment_Description_large car',
    'Segment_Description_large premium car',
    'Segment_Description_midsize car',
    'Segment_Description_midsize premium car',
    'Segment_Description_midsize sporty',
    'Segment_Description_midsize truck',
    'Segment_Description_small car',
    'Segment_Description_unknown',
]

columns_Cylinders = [
    'Cylinders_unknown',
    'Cylinders_v6',
    'Cylinders_v8',
]

columns_Transmission = [
    'Transmission_automatic',
    'Transmission_manual',
    'Transmission_unknown',
]
columns_Displacement = [
    'Displacement_3l+',
    'Displacement_under 3l',
    'Displacement_unknown',
]

columns_lead_ProviderService = [
    'lead_ProviderService_autobytel  - trilogy smartleads',
    'lead_ProviderService_autobytel - trilogy smartleads',
    'lead_ProviderService_autolist - trilogy smartleads',
    'lead_ProviderService_automotive - trilogy smartleads',
    'lead_ProviderService_autopricefinder - trilogy smartleads',
    'lead_ProviderService_autosite  - trilogy smartleads',
    'lead_ProviderService_autosite - trilogy smartleads',
    'lead_ProviderService_autotegrity  - trilogy smartleads',
    'lead_ProviderService_autotegrity - trilogy smartleads',
    'lead_ProviderService_blackbook credit - trilogy smartleads',
    'lead_ProviderService_blackbook trade-in - trilogy smartleads',
    'lead_ProviderService_blackbook tradein - trilogy smartleads',
    'lead_ProviderService_bluesky - trilogy smartleads',
    'lead_ProviderService_buyerlink - trilogy smartleads',
    'lead_ProviderService_buyingadvice - trilogy smartleads',
    'lead_ProviderService_car.com  - trilogy smartleads',
    'lead_ProviderService_car.com - trilogy smartleads',
    'lead_ProviderService_cargurus - trilogy smartleads',
    'lead_ProviderService_carhub - trilogy smartleads',
    'lead_ProviderService_condurre - trilogy smartleads',
    'lead_ProviderService_consumernet - trilogy smartleads',
    'lead_ProviderService_cyberventures  - trilogy smartleads',
    'lead_ProviderService_cyberventures - trilogy smartleads',
    'lead_ProviderService_dt premier - trilogy smartleads',
    'lead_ProviderService_dtx  - trilogy smartleads',
    'lead_ProviderService_dtx - trilogy smartleads',
    'lead_ProviderService_edmunds - trilogy smartleads',
    'lead_ProviderService_edmunds carcode - trilogy smartleads',
    'lead_ProviderService_edmunds my appraise - trilogy smartleads',
    'lead_ProviderService_edmunds myappraise - trilogy smartleads',
    'lead_ProviderService_everyauto - trilogy smartleads',
    'lead_ProviderService_getauto - trilogy smartleads',
    'lead_ProviderService_iseecars - trilogy smartleads',
    'lead_ProviderService_jumpstart - trilogy smartleads',
    'lead_ProviderService_kelleybluebook - trilogy smartleads',
    'lead_ProviderService_leadfinder - trilogy smartleads',
    'lead_ProviderService_newcars  - trilogy smartleads',
    'lead_ProviderService_newcars - trilogy smartleads',
    'lead_ProviderService_qla - trilogy smartleads',
    'lead_ProviderService_topautoleads  - trilogy smartleads',
    'lead_ProviderService_topautoleads - trilogy smartleads',
    'lead_ProviderService_trilogy smartleads  -  blackbook credit ',
    'lead_ProviderService_trilogy smartleads - autobytel - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - autolist - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - automotive - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - blackbook credit - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - blackbook tradein - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - dtx - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - getauto - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - qla - trilogy smart leads',
    'lead_ProviderService_trilogy smartleads - vast - trilogy smart leads',
    'lead_ProviderService_usnews - trilogy smartleads',
    'lead_ProviderService_vast - trilogy smartleads',
    'lead_ProviderService_web2carz - trilogy smartleads',
]

columns_Period = [
    'Period_2017-01',
    'Period_2017-02',
    'Period_2017-03',
    'Period_2017-04',
    'Period_2017-05',
    'Period_2017-06',
    'Period_2017-07',
    'Period_2017-08',
    'Period_2017-09',
    'Period_2017-10',
    'Period_2017-11',
    'Period_2017-12',
]

columns_Model = [
    'Model_accent',
    'Model_accent 4-door',
    'Model_accent value ed',
    'Model_accent???',
    'Model_any',
    'Model_azer',
    'Model_azera',
    'Model_elantra',
    'Model_elantra coupe',
    'Model_elantra gt',
    'Model_elantra lim pze',
    'Model_elantra ltd pzev',
    'Model_elantra se',
    'Model_equus',
    'Model_g80',
    'Model_g90',
    'Model_genesis',
    'Model_genesis coupe',
    'Model_genesis sedan',
    'Model_genesis-coupe',
    'Model_ioniq',
    'Model_ioniq electric',
    'Model_ioniq ev',
    'Model_ioniq hybrid',
    'Model_ioniq-hybrid',
    'Model_lacrosse',
    'Model_santa  fe',
    'Model_santa fe',
    'Model_santa fe s',
    'Model_santa fe se',
    'Model_santa fe sport',
    'Model_santa-fe',
    'Model_santa-fe-sport',
    'Model_sonata',
    'Model_sonata hybrid',
    'Model_sonata hybrid se',
    'Model_sonata plug-in hybrid',
    'Model_sonata sport 2.4l pzev',
    'Model_sonata-hybrid',
    'Model_sonata-plug-in-hybrid',
    'Model_sonata???',
    'Model_taurus',
    'Model_tucson',
    'Model_unspecified',
    'Model_veloster',
    'Model_veloster turbo'
]

columns_Lead_Source = [
    'Lead_Source_ blackbook credit ',
    'Lead_Source_hyundaiusa',
    'Lead_Source_trilogy smartleads'
]

js = {
    "DistanctToVendor": 0.0,
    "FirstLastPropCase": 0,
    "NameEmailCheck": 1,
    "SingleHour": 22,
    "SingleWeekday": "Friday",
    "lead_TimeFrameCont": "0-3 Months",
    "EmailDomainCat": "normal",
    "Vehicle_FinanceMethod": "unknown",
    "BroadColour": "WHITE",
    "ColoursNotChosen": 0,
    "Gender": "?",
    "Income": "55319.38839868469",
    "ZipPopulationDensity": "3585.807443350386",
    "ZipPopulationDensity_AverageUsed": 0,
    "CountryOfOrigin": "USA",
    "AddressProvided": 1,
    "TelephonePreference": "day",
    "AddressContainsNumericAndText": 1,
    "Segment_Description": "unknown",
    "PriceStart": "31295",
    "Cylinders": "UNKNOWN",
    "Hybrid": 0,
    "Transmission": "UNKNOWN",
    "Displacement": "under3l",
    "lead_ProviderService": "Hyundai Drive",
    "LeadConverted": 0,
    "Period": "2017-12",
    "Model": "Santa Fe",
    "Lead_Source": "hyundaiusa",
    "Rating": "4.678555302965422",
    "LifeTimeReviews": "228.7548938307518",
    "Recommended": "95.71456599706488",
    "SCR": "5.348490632243166",
    "OCR": "8.918993057558286"
}

a = ['DistanctToVendor',
     'FirstLastPropCase',
     'NameEmailCheck',
     'SingleHour',
     'ColoursNotChosen',
     'Income',
     'ZipPopulationDensity',
     'ZipPopulationDensity_AverageUsed',
     'AddressProvided',
     'AddressContainsNumericAndText',
     'PriceStart',
     'Hybrid',
     'Rating',
     'LifeTimeReviews',
     'Recommended',
     'SCR',
     'OCR',
     'SingleWeekday_Sunday',
     'SingleWeekday_friday',
     'SingleWeekday_monday',
     'SingleWeekday_saturday',
     'SingleWeekday_sunday',
     'SingleWeekday_thursday',
     'SingleWeekday_tuesday',
     'SingleWeekday_wednesday',
     'lead_TimeFrameCont_1 month',
     'lead_TimeFrameCont_2 weeks',
     'lead_TimeFrameCont_3 months',
     'lead_TimeFrameCont_beyond 3 months',
     'lead_TimeFrameCont_unknown',
     'EmailDomainCat_high',
     'EmailDomainCat_low',
     'EmailDomainCat_normal',
     'Vehicle_FinanceMethod_cash',
     'Vehicle_FinanceMethod_finance',
     'Vehicle_FinanceMethod_lease',
     'Vehicle_FinanceMethod_unknown',
     'BroadColour_beige',
     'BroadColour_black',
     'BroadColour_blue',
     'BroadColour_bronze',
     'BroadColour_gray',
     'BroadColour_green',
     'BroadColour_no preference',
     'BroadColour_orange',
     'BroadColour_red',
     'BroadColour_silver',
     'BroadColour_unknown',
     'BroadColour_white',
     'BroadColour_yellow',
     'Gender_1f',
     'Gender_1m',
     'Gender_?',
     'Gender_?f',
     'Gender_?m',
     'Gender_f',
     'Gender_m',
     'Gender_unknown',
     'CountryOfOrigin_asian',
     'CountryOfOrigin_east_asian_other',
     'CountryOfOrigin_europe',
     'CountryOfOrigin_unknown',
     'CountryOfOrigin_usa ',
     'TelephonePreference_afternoon',
     'TelephonePreference_day',
     'TelephonePreference_evening',
     'TelephonePreference_morning',
     'TelephonePreference_nopreference',
     'TelephonePreference_unknown',
     'Segment_Description_compact truck',
     'Segment_Description_large car',
     'Segment_Description_large premium car',
     'Segment_Description_midsize car',
     'Segment_Description_midsize premium car',
     'Segment_Description_midsize sporty',
     'Segment_Description_midsize truck',
     'Segment_Description_small car',
     'Segment_Description_unknown',
     'Cylinders_unknown',
     'Cylinders_v6',
     'Cylinders_v8',
     'Transmission_automatic',
     'Transmission_manual',
     'Transmission_unknown',
     'Displacement_3l+',
     'Displacement_under 3l',
     'Displacement_unknown',
     'lead_ProviderService_autobytel  - trilogy smartleads',
     'lead_ProviderService_autobytel - trilogy smartleads',
     'lead_ProviderService_autolist - trilogy smartleads',
     'lead_ProviderService_automotive - trilogy smartleads',
     'lead_ProviderService_autopricefinder - trilogy smartleads',
     'lead_ProviderService_autosite  - trilogy smartleads',
     'lead_ProviderService_autosite - trilogy smartleads',
     'lead_ProviderService_autotegrity  - trilogy smartleads',
     'lead_ProviderService_autotegrity - trilogy smartleads',
     'lead_ProviderService_blackbook credit - trilogy smartleads',
     'lead_ProviderService_blackbook trade-in - trilogy smartleads',
     'lead_ProviderService_blackbook tradein - trilogy smartleads',
     'lead_ProviderService_bluesky - trilogy smartleads',
     'lead_ProviderService_buyerlink - trilogy smartleads',
     'lead_ProviderService_buyingadvice - trilogy smartleads',
     'lead_ProviderService_car.com  - trilogy smartleads',
     'lead_ProviderService_car.com - trilogy smartleads',
     'lead_ProviderService_cargurus - trilogy smartleads',
     'lead_ProviderService_carhub - trilogy smartleads',
     'lead_ProviderService_condurre - trilogy smartleads',
     'lead_ProviderService_consumernet - trilogy smartleads',
     'lead_ProviderService_cyberventures  - trilogy smartleads',
     'lead_ProviderService_cyberventures - trilogy smartleads',
     'lead_ProviderService_dt premier - trilogy smartleads',
     'lead_ProviderService_dtx  - trilogy smartleads',
     'lead_ProviderService_dtx - trilogy smartleads',
     'lead_ProviderService_edmunds - trilogy smartleads',
     'lead_ProviderService_edmunds carcode - trilogy smartleads',
     'lead_ProviderService_edmunds my appraise - trilogy smartleads',
     'lead_ProviderService_edmunds myappraise - trilogy smartleads',
     'lead_ProviderService_everyauto - trilogy smartleads',
     'lead_ProviderService_getauto - trilogy smartleads',
     'lead_ProviderService_iseecars - trilogy smartleads',
     'lead_ProviderService_jumpstart - trilogy smartleads',
     'lead_ProviderService_kelleybluebook - trilogy smartleads',
     'lead_ProviderService_leadfinder - trilogy smartleads',
     'lead_ProviderService_newcars  - trilogy smartleads',
     'lead_ProviderService_newcars - trilogy smartleads',
     'lead_ProviderService_qla - trilogy smartleads',
     'lead_ProviderService_topautoleads  - trilogy smartleads',
     'lead_ProviderService_topautoleads - trilogy smartleads',
     'lead_ProviderService_trilogy smartleads  -  blackbook credit ',
     'lead_ProviderService_trilogy smartleads - autobytel - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - autolist - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - automotive - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - blackbook credit - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - blackbook tradein - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - dtx - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - getauto - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - qla - trilogy smart leads',
     'lead_ProviderService_trilogy smartleads - vast - trilogy smart leads',
     'lead_ProviderService_usnews - trilogy smartleads',
     'lead_ProviderService_vast - trilogy smartleads',
     'lead_ProviderService_web2carz - trilogy smartleads',
     'Period_2017-01',
     'Period_2017-02',
     'Period_2017-03',
     'Period_2017-04',
     'Period_2017-05',
     'Period_2017-06',
     'Period_2017-07',
     'Period_2017-08',
     'Period_2017-09',
     'Period_2017-10',
     'Period_2017-11',
     'Period_2017-12',
     'Model_accent',
     'Model_accent 4-door',
     'Model_accent value ed',
     'Model_accent???',
     'Model_any',
     'Model_azer',
     'Model_azera',
     'Model_elantra',
     'Model_elantra coupe',
     'Model_elantra gt',
     'Model_elantra lim pze',
     'Model_elantra ltd pzev',
     'Model_elantra se',
     'Model_equus',
     'Model_g80',
     'Model_g90',
     'Model_genesis',
     'Model_genesis coupe',
     'Model_genesis sedan',
     'Model_genesis-coupe',
     'Model_ioniq',
     'Model_ioniq electric',
     'Model_ioniq ev',
     'Model_ioniq hybrid',
     'Model_ioniq-hybrid',
     'Model_lacrosse',
     'Model_santa  fe',
     'Model_santa fe',
     'Model_santa fe s',
     'Model_santa fe se',
     'Model_santa fe sport',
     'Model_santa-fe',
     'Model_santa-fe-sport',
     'Model_sonata',
     'Model_sonata hybrid',
     'Model_sonata hybrid se',
     'Model_sonata plug-in hybrid',
     'Model_sonata sport 2.4l pzev',
     'Model_sonata-hybrid',
     'Model_sonata-plug-in-hybrid',
     'Model_sonata???',
     'Model_taurus',
     'Model_tucson',
     'Model_unspecified',
     'Model_veloster',
     'Model_veloster turbo',
     'Lead_Source_ blackbook credit ',
     'Lead_Source_hyundaiusa',
     'Lead_Source_trilogy smartleads']

remaining_columns = [
    'columns_single_weekday',
    'columns_lead_TimeFrame',
    'columns_EmailDomainCat',
    'columns_Vehicle_FinanceMethod',
    'columns_BroadColour',
    'columns_Gender',
    'columns_CountryOfOrigin',
    'columns_TelephonePreference',
    'columns_Segment_Description',
    'columns_Cylinders',
    'columns_Transmission',
    'columns_Displacement',
    'columns_lead_ProviderService',
    'columns_Period',
    'columns_Model',
    'columns_Lead_Source'
]

initial_ml_input = {
    "DistanctToVendor": 0,
    "FirstLastPropCase": 0,
    "NameEmailCheck": 0,
    "SingleHour": 0,
    "ColoursNotChosen": 0,
    "Income": 0,
    "ZipPopulationDensity": 0,
    "ZipPopulationDensity_AverageUsed": 0,
    "AddressProvided": 0,
    "AddressContainsNumericAndText": 0,
    "PriceStart": 0,
    "Hybrid": 0,
    "Rating": 0,
    "LifeTimeReviews": 0,
    "Recommended": 0,
    "SCR": 0,
    "OCR": 0,
    "SingleWeekday_Sunday": 0,
    "SingleWeekday_friday": 0,
    "SingleWeekday_monday": 0,
    "SingleWeekday_saturday": 0,
    "SingleWeekday_sunday": 0,
    "SingleWeekday_thursday": 0,
    "SingleWeekday_tuesday": 0,
    "SingleWeekday_wednesday": 0,
    "lead_TimeFrameCont_1 month": 0,
    "lead_TimeFrameCont_2 weeks": 0,
    "lead_TimeFrameCont_3 months": 0,
    "lead_TimeFrameCont_beyond 3 months": 0,
    "lead_TimeFrameCont_unknown": 0,
    "EmailDomainCat_high": 0,
    "EmailDomainCat_low": 0,
    "EmailDomainCat_normal": 0,
    "Vehicle_FinanceMethod_cash": 0,
    "Vehicle_FinanceMethod_finance": 0,
    "Vehicle_FinanceMethod_lease": 0,
    "Vehicle_FinanceMethod_unknown": 0,
    "BroadColour_beige": 0,
    "BroadColour_black": 0,
    "BroadColour_blue": 0,
    "BroadColour_bronze": 0,
    "BroadColour_gray": 0,
    "BroadColour_green": 0,
    "BroadColour_no preference": 0,
    "BroadColour_orange": 0,
    "BroadColour_red": 0,
    "BroadColour_silver": 0,
    "BroadColour_unknown": 0,
    "BroadColour_white": 0,
    "BroadColour_yellow": 0,
    "Gender_1f": 0,
    "Gender_1m": 0,
    "Gender_?": 0,
    "Gender_?f": 0,
    "Gender_?m": 0,
    "Gender_f": 0,
    "Gender_m": 0,
    "Gender_unknown": 0,
    "CountryOfOrigin_asian": 0,
    "CountryOfOrigin_east_asian_other": 0,
    "CountryOfOrigin_europe": 0,
    "CountryOfOrigin_unknown": 0,
    "CountryOfOrigin_usa ": 0,
    "TelephonePreference_afternoon": 0,
    "TelephonePreference_day": 0,
    "TelephonePreference_evening": 0,
    "TelephonePreference_morning": 0,
    "TelephonePreference_nopreference": 0,
    "TelephonePreference_unknown": 0,
    "Segment_Description_compact truck": 0,
    "Segment_Description_large car": 0,
    "Segment_Description_large premium car": 0,
    "Segment_Description_midsize car": 0,
    "Segment_Description_midsize premium car": 0,
    "Segment_Description_midsize sporty": 0,
    "Segment_Description_midsize truck": 0,
    "Segment_Description_small car": 0,
    "Segment_Description_unknown": 0,
    "Cylinders_unknown": 0,
    "Cylinders_v6": 0,
    "Cylinders_v8": 0,
    "Transmission_automatic": 0,
    "Transmission_manual": 0,
    "Transmission_unknown": 0,
    "Displacement_3l+": 0,
    "Displacement_under 3l": 0,
    "Displacement_unknown": 0,
    "lead_ProviderService_autobytel  - trilogy smartleads": 0,
    "lead_ProviderService_autobytel - trilogy smartleads": 0,
    "lead_ProviderService_autolist - trilogy smartleads": 0,
    "lead_ProviderService_automotive - trilogy smartleads": 0,
    "lead_ProviderService_autopricefinder - trilogy smartleads": 0,
    "lead_ProviderService_autosite  - trilogy smartleads": 0,
    "lead_ProviderService_autosite - trilogy smartleads": 0,
    "lead_ProviderService_autotegrity  - trilogy smartleads": 0,
    "lead_ProviderService_autotegrity - trilogy smartleads": 0,
    "lead_ProviderService_blackbook credit - trilogy smartleads": 0,
    "lead_ProviderService_blackbook trade-in - trilogy smartleads": 0,
    "lead_ProviderService_blackbook tradein - trilogy smartleads": 0,
    "lead_ProviderService_bluesky - trilogy smartleads": 0,
    "lead_ProviderService_buyerlink - trilogy smartleads": 0,
    "lead_ProviderService_buyingadvice - trilogy smartleads": 0,
    "lead_ProviderService_car.com  - trilogy smartleads": 0,
    "lead_ProviderService_car.com - trilogy smartleads": 0,
    "lead_ProviderService_cargurus - trilogy smartleads": 0,
    "lead_ProviderService_carhub - trilogy smartleads": 0,
    "lead_ProviderService_condurre - trilogy smartleads": 0,
    "lead_ProviderService_consumernet - trilogy smartleads": 0,
    "lead_ProviderService_cyberventures  - trilogy smartleads": 0,
    "lead_ProviderService_cyberventures - trilogy smartleads": 0,
    "lead_ProviderService_dt premier - trilogy smartleads": 0,
    "lead_ProviderService_dtx  - trilogy smartleads": 0,
    "lead_ProviderService_dtx - trilogy smartleads": 0,
    "lead_ProviderService_edmunds - trilogy smartleads": 0,
    "lead_ProviderService_edmunds carcode - trilogy smartleads": 0,
    "lead_ProviderService_edmunds my appraise - trilogy smartleads": 0,
    "lead_ProviderService_edmunds myappraise - trilogy smartleads": 0,
    "lead_ProviderService_everyauto - trilogy smartleads": 0,
    "lead_ProviderService_getauto - trilogy smartleads": 0,
    "lead_ProviderService_iseecars - trilogy smartleads": 0,
    "lead_ProviderService_jumpstart - trilogy smartleads": 0,
    "lead_ProviderService_kelleybluebook - trilogy smartleads": 0,
    "lead_ProviderService_leadfinder - trilogy smartleads": 0,
    "lead_ProviderService_newcars  - trilogy smartleads": 0,
    "lead_ProviderService_newcars - trilogy smartleads": 0,
    "lead_ProviderService_qla - trilogy smartleads": 0,
    "lead_ProviderService_topautoleads  - trilogy smartleads": 0,
    "lead_ProviderService_topautoleads - trilogy smartleads": 0,
    "lead_ProviderService_trilogy smartleads  -  blackbook credit ": 0,
    "lead_ProviderService_trilogy smartleads - autobytel - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - autolist - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - automotive - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - blackbook credit - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - blackbook tradein - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - dtx - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - getauto - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - qla - trilogy smart leads": 0,
    "lead_ProviderService_trilogy smartleads - vast - trilogy smart leads": 0,
    "lead_ProviderService_usnews - trilogy smartleads": 0,
    "lead_ProviderService_vast - trilogy smartleads": 0,
    "lead_ProviderService_web2carz - trilogy smartleads": 0,
    "Period_2017-01": 0,
    "Period_2017-02": 0,
    "Period_2017-03": 0,
    "Period_2017-04": 0,
    "Period_2017-05": 0,
    "Period_2017-06": 0,
    "Period_2017-07": 0,
    "Period_2017-08": 0,
    "Period_2017-09": 0,
    "Period_2017-10": 0,
    "Period_2017-11": 0,
    "Period_2017-12": 0,
    "Model_accent": 0,
    "Model_accent 4-door": 0,
    "Model_accent value ed": 0,
    "Model_accent???": 0,
    "Model_any": 0,
    "Model_azer": 0,
    "Model_azera": 0,
    "Model_elantra": 0,
    "Model_elantra coupe": 0,
    "Model_elantra gt": 0,
    "Model_elantra lim pze": 0,
    "Model_elantra ltd pzev": 0,
    "Model_elantra se": 0,
    "Model_equus": 0,
    "Model_g80": 0,
    "Model_g90": 0,
    "Model_genesis": 0,
    "Model_genesis coupe": 0,
    "Model_genesis sedan": 0,
    "Model_genesis-coupe": 0,
    "Model_ioniq": 0,
    "Model_ioniq electric": 0,
    "Model_ioniq ev": 0,
    "Model_ioniq hybrid": 0,
    "Model_ioniq-hybrid": 0,
    "Model_lacrosse": 0,
    "Model_santa  fe": 0,
    "Model_santa fe": 0,
    "Model_santa fe s": 0,
    "Model_santa fe se": 0,
    "Model_santa fe sport": 0,
    "Model_santa-fe": 0,
    "Model_santa-fe-sport": 0,
    "Model_sonata": 0,
    "Model_sonata hybrid": 0,
    "Model_sonata hybrid se": 0,
    "Model_sonata plug-in hybrid": 0,
    "Model_sonata sport 2.4l pzev": 0,
    "Model_sonata-hybrid": 0,
    "Model_sonata-plug-in-hybrid": 0,
    "Model_sonata???": 0,
    "Model_taurus": 0,
    "Model_tucson": 0,
    "Model_unspecified": 0,
    "Model_veloster": 0,
    "Model_veloster turbo": 0,
    "Lead_Source_blackbook credit ": 0,
    "Lead_Source_hyundaiusa": 0,
    "Lead_Source_trilogy smartleads": 0
}


def conversion_to_ml_input(data):
    ml_input = []
    # for column_name in columns_list:
    #     ml_input.append(float(data[column_name]))
    # for remaining_column in remaining_columns:
    #     pass

    # for column_name in a:
    #     # if column_name in columns_list:
    #     #     ml_input.append(float(data[column_name]))
    #     # else:
    #     print(f"\"{column_name}\": 0,")

    ml_data_json = initial_ml_input
    for key in data:
        if key in columns_list:
            ml_data_json[key] = float(data[key])
        else:
            new_key = f"{key}_{data[key]}"
            if new_key in ml_data_json:
                ml_data_json[new_key] = 1

    for key in ml_data_json:
        ml_input.append(ml_data_json[key])

        # print(key, data[key])
    return ml_input
