column_list_mas_dealer = ['DistanctToVendor',
                          'FirstLastPropCase',
                          'NameEmailCheck',
                          'NamenMail_Proper',
                          'SingleHour',
                          'ColoursNotChosen',
                          'Color_Selected',
                          'Income',
                          'ZipPopulationDensity',
                          'AddressProvided',
                          'AddressContainsNumericAndText',
                          'ProperAddress',
                          'PriceStart',
                          'Rating',
                          'LifeTimeReviews',
                          'Recommend',
                          'EmailDomainCat_Ratio',
                          'lead_ProviderService_Ratio']

initial_ml_input_mas_dealer = {
    "DistanctToVendor": 0,
    "FirstLastPropCase": 0,
    "NameEmailCheck": 0,
    "NamenMail_Proper": 0,
    "SingleHour": 0,
    "ColoursNotChosen": 0,
    "Color_Selected": 0,
    "Income": 0,
    "ZipPopulationDensity": 0,
    "AddressProvided": 0,
    "AddressContainsNumericAndText": 0,
    "ProperAddress": 0,
    "PriceStart": 0,
    "Rating": 0,
    "LifeTimeReviews": 0,
    "Recommend": 0,
    "SingleWeekday_friday": 0,
    "SingleWeekday_monday": 0,
    "SingleWeekday_saturday": 0,
    "SingleWeekday_sunday": 0,
    "SingleWeekday_thursday": 0,
    "SingleWeekday_tuesday": 0,
    "SingleWeekday_wednesday": 0,
    "lead_TimeFrameCont_1 month": 0,
    "lead_TimeFrameCont_1 week": 0,
    "lead_TimeFrameCont_2 days": 0,
    "lead_TimeFrameCont_2 weeks": 0,
    "lead_TimeFrameCont_unknown": 0,
    "Vehicle_FinanceMethod_cash": 0,
    "Vehicle_FinanceMethod_finance": 0,
    "Vehicle_FinanceMethod_lease": 0,
    "Vehicle_FinanceMethod_unknown": 0,
    "BroadColour_beige": 0,
    "BroadColour_black": 0,
    "BroadColour_blue": 0,
    "BroadColour_bronze": 0,
    "BroadColour_gray": 0,
    "BroadColour_green": 0,
    "BroadColour_no preference": 0,
    "BroadColour_orange": 0,
    "BroadColour_red": 0,
    "BroadColour_silver": 0,
    "BroadColour_unknown": 0,
    "BroadColour_white": 0,
    "BroadColour_yellow": 0,
    "Gender_cat_female": 0,
    "Gender_cat_male": 0,
    "Gender_cat_unknown": 0,
    "CountryOfOrigin_asian": 0,
    "CountryOfOrigin_east_asian_other": 0,
    "CountryOfOrigin_europe": 0,
    "CountryOfOrigin_unknown": 0,
    "CountryOfOrigin_usa ": 0,
    "TelephonePreference_afternoon": 0,
    "TelephonePreference_day": 0,
    "TelephonePreference_daytime": 0,
    "TelephonePreference_evening": 0,
    "TelephonePreference_evening-weekend": 0,
    "TelephonePreference_morning": 0,
    "TelephonePreference_nopreference": 0,
    "TelephonePreference_unknown": 0,
    "Segment_Description_large premium car": 0,
    "Segment_Description_midsize premium car": 0,
    "Segment_Description_midsize premium truck": 0,
    "Segment_Description_small premium car": 0,
    "Segment_Description_small premium sporty": 0,
    "Segment_Description_small premium truck": 0,
    "Segment_Description_unknown": 0,
    "Period_2015-01": 0,
    "Period_2015-02": 0,
    "Period_2015-03": 0,
    "Period_2015-04": 0,
    "Period_2015-05": 0,
    "Period_2015-06": 0,
    "Period_2015-07": 0,
    "Period_2015-08": 0,
    "Period_2015-09": 0,
    "Period_2015-10": 0,
    "Period_2015-11": 0,
    "Period_2015-12": 0,
    "SCR_cat_good": 0,
    "SCR_cat_normal": 0,
    "SCR_cat_worst": 0,
    "OCR_cat_good": 0,
    "OCR_cat_normal": 0,
    "OCR_cat_worst": 0,
    "EmailDomainCat_Ratio": 0.04438530340664647,
    "lead_ProviderService_Ratio": 0.044290802250891076,
}
